Repository uaem-na/donations-tracker, pull requests merged in 2023-07, with the labels that each got.

#31 Display a list of users by type and verify org user account
  README.md
  backend/controllers/auth.controller.ts
  backend/controllers/user.controller.ts
  backend/middlewares/ensureAdmin.ts
  backend/middlewares/index.ts
  backend/models/common/address.schema.ts
  backend/models/users/user.dto.ts
  backend/models/users/user.model.ts
  backend/models/users/user.organization.model.ts
  backend/routes/user.routes.ts
  backend/services/user.service.ts
  backend/types.ts
  frontend/src/app.js
  frontend/src/pages/index.js
  frontend/src/pages/usersAdministration.js
  frontend/src/store/services/users.js
Labels: enhancement

#32 Seed database
  README.md
  backend/constants/index.ts
  backend/middlewares/ensureAdmin.ts
  backend/models/common/address.schema.ts
  backend/models/common/location.schema.ts
  backend/models/posts/index.ts
  backend/models/posts/post.base.model.ts
  backend/models/posts/post.dto.ts
  backend/models/posts/post.offer.model.ts
  backend/models/posts/post.request.model.ts
  backend/models/reports/report.dto.ts
  backend/models/reports/report.model.ts
  backend/models/users/index.ts
  backend/models/users/user.admin.model.ts
  backend/models/users/user.base.model.ts
  backend/models/users/user.dto.ts
  backend/models/users/user.individual.model.ts
  backend/models/users/user.organization.model.ts
  backend/package-lock.json
  backend/package.json
  backend/seeder/index.ts
  backend/seeder/seed.posts.ts
  backend/seeder/seed.reports.ts
  backend/seeder/seed.users.ts
  backend/types.ts
  frontend/src/app.js
  frontend/src/pages/admin/users.js
  frontend/src/pages/index.js
Labels: enhancement

#33 feat(app): initial ux rework
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/avatar/avatar.tsx
  frontend/src/components/header/desktopNav.tsx
  frontend/src/components/header/mobileNav.tsx
  frontend/src/components/header/siteLinks.tsx
  frontend/src/components/layouts/header/header.tsx
  frontend/src/components/layouts/header/index.ts
  frontend/src/components/layouts/header/profile/index.ts
  frontend/src/components/layouts/header/profile/profile.tsx
  frontend/src/components/layouts/index.ts
  frontend/src/components/layouts/sidebar/index.ts
  frontend/src/components/layouts/sidebar/sidebar.mobile.tsx
  frontend/src/components/layouts/sidebar/sidebar.tsx
  frontend/src/constants/siteLinks.ts
  frontend/src/layout/layout.tsx
  frontend/src/pages/about-us.tsx
  frontend/src/pages/about.tsx
  frontend/src/pages/faq.tsx
  frontend/src/pages/index.tsx
  frontend/src/utils/index.ts
  frontend/src/utils/utils.ts
Labels: enhancement, good first issue

#34 Features/frontend work
  frontend/package-lock.json
  frontend/package.json
  frontend/public/login_img.png
  frontend/src/app.tsx
  frontend/src/components/alert/alert.tsx
  frontend/src/components/alert/index.ts
  frontend/src/components/common/inputs/textInput.tsx
  frontend/src/components/common/typography/externalLink.tsx
  frontend/src/components/forms/index.ts
  frontend/src/components/forms/label/label.tsx
  frontend/src/components/forms/textbox/textbox.tsx
  frontend/src/features/auth/login-form.tsx
  frontend/src/pages/about-us.tsx
  frontend/src/pages/login.tsx
  frontend/tailwind.config.js
Labels: enhancement

#35 Features/pages
  backend/models/posts/post.dto.ts
  backend/types.ts
  frontend/src/app.tsx
  frontend/src/components/common/avatar/avatar.tsx
  frontend/src/components/common/icons/collapseIcon.tsx
  frontend/src/components/common/icons/expandIcon.tsx
  frontend/src/components/common/icons/index.ts
  frontend/src/components/common/index.ts
  frontend/src/components/common/tooltip/tooltip.tsx
  frontend/src/components/dashboard/offerLink.tsx
  frontend/src/components/dashboard/offers.tsx
  frontend/src/components/dashboard/requestLink.tsx
  frontend/src/components/globalStyles/globalStyles.tsx
  frontend/src/components/globalStyles/index.tsx
  frontend/src/components/header/desktopNav.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/header/userMenu.tsx
  frontend/src/components/landing.tsx
  frontend/src/components/layouts/header/header.tsx
  frontend/src/components/layouts/header/profile/profile.tsx
  frontend/src/components/layouts/sidebar/sidebar.mobile.tsx
  frontend/src/components/layouts/sidebar/sidebar.tsx
  frontend/src/components/map/Map.tsx
  frontend/src/features/auth/index.ts
  frontend/src/features/auth/login-form.tsx
  frontend/src/features/auth/registerForm.tsx
  frontend/src/features/auth/requireAuth.tsx
  frontend/src/features/posts/addItem.tsx
  frontend/src/features/posts/createPostForm.tsx
  frontend/src/features/posts/index.ts
  frontend/src/features/users/index.ts
  frontend/src/features/users/updatePasswordForm.tsx
  frontend/src/features/users/updateUserInfoForm.tsx
  frontend/src/index.tsx
  frontend/src/layout/layout.tsx
  frontend/src/pages/about-us.tsx
  frontend/src/pages/account.tsx
  frontend/src/pages/admin/users.tsx
  frontend/src/pages/faq.tsx
  frontend/src/pages/index.ts
  frontend/src/pages/index.tsx
  frontend/src/pages/landing.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/posts/create.tsx
  frontend/src/pages/register.tsx
  frontend/src/pages/requestOfferPage/reqOff.tsx
  frontend/src/pages/requestOfferPage/sections/editppe.tsx
  frontend/src/pages/requestOfferPage/sections/location.tsx
  frontend/src/pages/requestOfferPage/sections/viewppe.tsx
  frontend/src/store/index.ts
  frontend/src/store/services/auth.ts
  frontend/src/store/services/posts.ts
  frontend/src/store/services/users.ts
  frontend/tsconfig.json
Labels: enhancement

#36 feat(app): registration page redesign
  frontend/src/components/alert/alert.tsx
  frontend/src/components/common/button/Button.tsx
  frontend/src/components/common/button/button.tsx
  frontend/src/components/common/button/index.tsx
  frontend/src/components/forms/index.ts
  frontend/src/components/forms/label/Label.tsx
  frontend/src/components/forms/textbox/Textbox.tsx
  frontend/src/features/auth/LoginForm.tsx
  frontend/src/features/auth/RegisterForm.tsx
  frontend/src/features/auth/index.ts
  frontend/src/features/auth/registerForm.tsx
  frontend/src/features/yupSchemas.ts
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
  frontend/src/pages/index.ts
  frontend/src/pages/register.tsx
Labels: enhancement

#37 Features/admin
  README.md
  backend/controllers/user.controller.ts
  backend/models/posts/post.dto.ts
  backend/models/reports/report.dto.ts
  backend/models/users/user.dto.ts
  backend/routes/user.routes.ts
  backend/services/user.service.ts
  backend/types.ts
  frontend/src/app.tsx
  frontend/src/components/common/tooltip/tooltip.tsx
  frontend/src/components/layouts/sidebar/sidebar.mobile.tsx
  frontend/src/components/layouts/sidebar/sidebar.tsx
  frontend/src/constants/index.tsx
  frontend/src/constants/siteLinks.ts
  frontend/src/features/auth/requireAuth.tsx
  frontend/src/pages/admin/components/user-table.tsx
  frontend/src/pages/admin/users.tsx
  frontend/src/pages/index.ts
  frontend/src/pages/posts/components/post-table.tsx
  frontend/src/pages/posts/offers.tsx
  frontend/src/pages/posts/requests.tsx
  frontend/src/store/services/posts.ts
  frontend/src/store/services/users.ts
  frontend/src/utils/capitalizeFirstLetter.ts
  frontend/src/utils/index.ts
Labels: enhancement

#38 fixes style of map on landing page
  frontend/src/components/map/GoogleMapWrapper.tsx
  frontend/src/pages/landing.tsx
Labels: bug

#41 ✨ feat(app): redesign account page
  frontend/src/components/Controls/Button/Button.tsx
  frontend/src/components/Toast/Toast.tsx
  frontend/src/components/Toast/ToastProvider.tsx
  frontend/src/components/Toast/index.ts
  frontend/src/components/Toast/useToast.ts
  frontend/src/components/index.ts
  frontend/src/features/users/UpdatePasswordForm.tsx
  frontend/src/features/users/UpdateUserInfoForm.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useTimeout.ts
  frontend/src/index.tsx
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/pages/Account/Security.tsx
  frontend/src/store/services/posts.ts
  frontend/src/utils/GenerateRandomID.ts
Labels: enhancement

#42 adds barebone post create & list & detail
  README.md
  backend/constants/index.ts
  backend/controllers/post.controller.ts
  backend/errors/httpError.ts
  backend/errors/validationError.ts
  backend/middlewares/errorHandler.ts
  backend/models/posts/post.base.model.ts
  backend/models/posts/post.dto.ts
  backend/models/reports/report.dto.ts
  backend/models/users/user.dto.ts
  backend/routes/post.routes.ts
  backend/services/post.service.ts
  backend/types.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/common.json
  frontend/public/locales/en/glossary.json
  frontend/public/locales/en/validation.json
  frontend/public/locales/fr/common.json
  frontend/public/locales/fr/glossary.json
  frontend/public/locales/fr/validation.json
  frontend/src/app.tsx
  frontend/src/components/Controls/Select/SelectInput.tsx
  frontend/src/components/Controls/Select/index.ts
  frontend/src/components/Layouts/Header/Profile/Profile.tsx
  frontend/src/features/posts/AddItem.tsx
  frontend/src/features/posts/CreatePostForm.tsx
  frontend/src/features/posts/index.ts
  frontend/src/i18n.ts
  frontend/src/index.tsx
  frontend/src/pages/Posts/Create.tsx
  frontend/src/pages/Posts/CreateOffer.tsx
  frontend/src/pages/Posts/CreateRequest.tsx
  frontend/src/pages/Posts/OfferDetails.tsx
  frontend/src/pages/Posts/RequestDetails.tsx
  frontend/src/pages/Posts/components/CreatePostForm.tsx
  frontend/src/pages/Posts/components/PostDetails.tsx
  frontend/src/pages/Posts/components/PostTable.tsx
  frontend/src/pages/Posts/components/SelectInput.tsx
  frontend/src/pages/Posts/components/schemas/CreatePostFormSchema.ts
  frontend/src/pages/Posts/index.ts
  frontend/src/pages/index.ts
  frontend/src/store/services/posts.ts
  frontend/tsconfig.json
Labels: enhancement

#43 fix bugs on render
  backend/services/post.service.ts
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/store/services/posts.ts
Labels: bug
