Repository uaem-na/donations-tracker, pull requests merged in 2023-08, with the labels that each got.

#46 features/landing page
  .env.sample
  README.md
  docker-compose.yml
  frontend/Dockerfile.local
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Alert/Alert.tsx
  frontend/src/components/Badge/Badge.tsx
  frontend/src/components/Badge/index.ts
  frontend/src/components/Drawer/Drawer.tsx
  frontend/src/components/Drawer/DrawerContent.tsx
  frontend/src/components/Drawer/DrawerDescription.tsx
  frontend/src/components/Drawer/DrawerFooter.tsx
  frontend/src/components/Drawer/DrawerHeader.tsx
  frontend/src/components/Drawer/DrawerOverlay.tsx
  frontend/src/components/Drawer/DrawerPortal.tsx
  frontend/src/components/Drawer/DrawerTitle.tsx
  frontend/src/components/Drawer/index.ts
  frontend/src/components/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/GoogleMapWrapper/InfoBox.tsx
  frontend/src/components/GoogleMapWrapper/Locate.tsx
  frontend/src/components/GoogleMapWrapper/MapStyles.ts
  frontend/src/components/GoogleMapWrapper/MarkerUtils.ts
  frontend/src/components/GoogleMapWrapper/Offer.tsx
  frontend/src/components/GoogleMapWrapper/Request.tsx
  frontend/src/components/GoogleMapWrapper/index.css
  frontend/src/components/Posts/PostDetails.tsx
  frontend/src/components/StatusIndicator/StatusIndicator.tsx
  frontend/src/components/StatusIndicator/index.ts
  frontend/src/layout/Layout.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Landing/components/Posts.tsx
  frontend/src/pages/Posts/OfferDetails.tsx
  frontend/src/pages/Posts/RequestDetails.tsx
  frontend/src/pages/Posts/components/PostDetails.tsx
  frontend/src/utils/ClassMerge.ts
  frontend/src/utils/GeoCluster.ts
  frontend/src/vite-env.d.tsx
Labels: enhancement

#47 limit # of item per post
  backend/constants/index.ts
  backend/controllers/post.controller.ts
  backend/models/posts/post.base.model.ts
  backend/models/posts/post.dto.ts
  backend/models/posts/post.offer.model.ts
  backend/models/posts/post.request.model.ts
  backend/seeder/seed.posts.ts
  backend/services/post.service.ts
  backend/types.ts
  frontend/src/pages/Posts/components/CreatePostForm.tsx
  frontend/src/pages/Posts/components/EditPostForm.tsx
  frontend/src/pages/Posts/components/PostTable.tsx
  frontend/src/pages/Posts/components/schemas/CreateEditPostSchema.ts
  frontend/src/pages/Posts/components/schemas/CreatePostFormSchema.ts
  frontend/src/pages/Posts/components/schemas/EditPostFormSchema.ts
  frontend/src/store/services/posts.ts
Labels: bug

#48 Enhances marker behaviours
  frontend/src/components/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/utils/GeoCluster.ts
Labels: enhancement

#49 Removes title from post
  backend/controllers/post.controller.ts
  backend/controllers/report.controller.ts
  backend/models/posts/post.base.model.ts
  backend/models/posts/post.dto.ts
  backend/types.ts
  frontend/src/features/auth/LoginForm.tsx
  frontend/src/pages/Posts/components/CreatePostForm.tsx
  frontend/src/pages/Posts/components/EditPostForm.tsx
  frontend/src/pages/Posts/components/PostTable.tsx
  frontend/src/pages/Posts/components/schemas/CreateEditPostSchema.ts
  frontend/src/pages/Register/Register.tsx
  frontend/src/store/services/posts.ts
Labels: bug

#50 Adds tracking posts
  README.md
  backend/controllers/post.controller.ts
  backend/controllers/user.controller.ts
  backend/models/common/index.ts
  backend/models/common/location.dto.ts
  backend/models/posts/post.dto.ts
  backend/models/users/user.admin.model.ts
  backend/models/users/user.base.model.ts
  backend/models/users/user.dto.ts
  backend/models/users/user.individual.model.ts
  backend/routes/post.routes.ts
  backend/routes/user.routes.ts
  backend/services/post.service.ts
  backend/services/user.service.ts
  backend/types.ts
  frontend/public/locales/en/common.json
  frontend/public/locales/fr/common.json
  frontend/src/app.tsx
  frontend/src/components/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/Layouts/Header/Profile/Profile.tsx
  frontend/src/components/Layouts/Sidebar/Sidebar.tsx
  frontend/src/components/Layouts/Sidebar/SidebarMobile.tsx
  frontend/src/components/Posts/PostDetails.tsx
  frontend/src/components/Posts/PostItem.tsx
  frontend/src/components/Posts/PostList.tsx
  frontend/src/components/Posts/PostsContainer.tsx
  frontend/src/components/Posts/index.ts
  frontend/src/components/index.ts
  frontend/src/constants/SiteLinks.ts
  frontend/src/features/auth/LoginForm.tsx
  frontend/src/features/auth/RequireAuth.tsx
  frontend/src/features/users/UpdatePasswordForm.tsx
  frontend/src/features/users/UpdateUserInfoForm.tsx
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/pages/Account/General.tsx
  frontend/src/pages/Admin/components/UserTable.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Landing/components/Posts.tsx
  frontend/src/pages/Posts/CreateOffer.tsx
  frontend/src/pages/Posts/CreatePost.tsx
  frontend/src/pages/Posts/CreateRequest.tsx
  frontend/src/pages/Posts/EditOffer.tsx
  frontend/src/pages/Posts/EditPost.tsx
  frontend/src/pages/Posts/EditRequest.tsx
  frontend/src/pages/Posts/Offers.tsx
  frontend/src/pages/Posts/PostDetails.tsx
  frontend/src/pages/Posts/Posts.tsx
  frontend/src/pages/Posts/Requests.tsx
  frontend/src/pages/Posts/components/CreatePostForm.tsx
  frontend/src/pages/Posts/components/EditPostForm.tsx
  frontend/src/pages/Posts/components/PostTable.tsx
  frontend/src/pages/Posts/index.ts
  frontend/src/pages/Register/Register.tsx
  frontend/src/pages/Register/components/IndividualRegistrationForm.tsx
  frontend/src/pages/Register/components/OrganizationRegistrationForm.tsx
  frontend/src/store/index.ts
  frontend/src/store/services/api.ts
  frontend/src/store/services/auth.ts
  frontend/src/store/services/posts.ts
  frontend/src/store/services/users.ts
Labels: bug, enhancement

#52 Paginating posts
  README.md
  backend/constants/index.ts
  backend/controllers/post.controller.ts
  backend/controllers/user.controller.ts
  backend/routes/user.routes.ts
  backend/services/post.service.ts
  backend/services/user.service.ts
  backend/types.ts
  backend/utils/isEnumValue.ts
  frontend/public/locales/en/common.json
  frontend/public/locales/fr/common.json
  frontend/src/components/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/Posts/PostsContainer.tsx
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/pages/Posts/Posts.tsx
  frontend/src/pages/Posts/components/CreatePostForm.tsx
  frontend/src/pages/Posts/components/PostTable.tsx
  frontend/src/store/services/api.ts
Labels: enhancement

#56 Enhances post related pages
  README.md
  frontend/public/locales/en/common.json
  frontend/public/locales/fr/common.json
  frontend/src/components/Badge/Badge.tsx
  frontend/src/components/Posts/FilterContainer.tsx
  frontend/src/components/Posts/PostItem.tsx
  frontend/src/components/Posts/PostList.tsx
  frontend/src/components/Posts/PostsContainer.tsx
  frontend/src/components/Posts/index.ts
  frontend/src/components/Posts/types.ts
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/pages/Posts/Posts.tsx
  frontend/src/store/services/api.ts
Labels: enhancement

#57 Add filtering posts on listings
  backend/constants/index.ts
  backend/controllers/post.controller.ts
  backend/controllers/user.controller.ts
  backend/controllers/validators/index.ts
  backend/controllers/validators/validateLocale.ts
  backend/controllers/validators/validatePaginationRequest.ts
  backend/controllers/validators/validatePostsFilterRequest.ts
  backend/models/posts/post.base.model.ts
  backend/routes/post.routes.ts
  backend/seeder/seed.posts.ts
  backend/services/post.service.ts
  backend/services/user.service.ts
  backend/types.ts
  backend/utils/index.ts
  backend/utils/tryParsePaginationQuery.ts
  backend/utils/tryParsePostFilterQuery.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/common.json
  frontend/public/locales/fr/common.json
  frontend/src/components/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/Posts/FilterContainer.tsx
  frontend/src/components/Posts/PostDetails.tsx
  frontend/src/components/Posts/PostItem.tsx
  frontend/src/components/Posts/PostsContainer.tsx
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/pages/Posts/Posts.tsx
  frontend/src/pages/Posts/components/CreatePostForm.tsx
  frontend/src/pages/Posts/components/EditPostForm.tsx
  frontend/src/store/services/api.ts
Labels: enhancement

#58 Filter layout and User's Posts
  backend/controllers/post.controller.ts
  backend/routes/post.routes.ts
  frontend/public/locales/en/common.json
  frontend/public/locales/fr/common.json
  frontend/src/components/Posts/FilterContainer.tsx
  frontend/src/components/Posts/FilterLayout.tsx
  frontend/src/components/Posts/PostsContainer.tsx
  frontend/src/pages/Account/Dashboard.tsx
  frontend/src/pages/Account/components/AccountLayout.tsx
  frontend/src/pages/Account/components/FavoritePosts.tsx
  frontend/src/pages/Account/components/MyPosts.tsx
  frontend/src/pages/Posts/Posts.tsx
  frontend/src/store/services/api.ts
Labels: enhancement
